export interface User {
  firstName: string,
  lastName: string,
  email: string,
  dob: string,
  password: string,
  mobileNumber: string,
  address1: string,
  address2: string,
  county: string,
  city: string,
  state: string,
  country: string,
  skills: string,
  licenseNumber: string,
  files: string,
  limitations: string,
  pushNotification: string,
  salt: string,
  token: string,
  role: string,
}
